# redis的配置
spring:
  redis:
    host: 192.168.16.181
    password: qwer
    port: 6379
    lettuce: # 连接池spring默认使用lettuce实现
      pool:
        max-active: 8  # 最大连接数
        max-idle: 8 # 最大空闲连接数
        min-idle: 0 # 最小空闲连接数
        max-wait: 1000 # 超时等待时间 ms