sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qwer
  alioss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucketName: java--web-learning
  redis:
    # 配置Spring Data Redis
    host: localhost
    port: 6379
    password: qwer
    database: 0
  wechat:
    appid: wxda0c680b0dac7bd1
    secret: 2c4a7ba212707c1e6a69dac01a714ebc