sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qwer
  alioss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucketName: java--web-learning
